<!-- Ce fichier correspond à la vue repris dans la variable $vue -->

<h1>Ajouter un utilisateur</h1>

<?php if ($erreur) {
    ?><p><?= $erreur; ?></p><?php
} ?>

<form method="POST" action="addUser.php">

    <p><label for="aut_name">Nom : </label><input type="text" name="aut_name" id="aut_name" value="<?= $resultats['aut_name']; ?>"/></p>

    <p><label for="aut_firstname">Prénom : </label><input type="text" name="aut_firstname" id="aut_firstname" value="<?= $resultats['aut_firstname']; ?>"/></p>

    <p><label for="aut_email">Email : </label><input type="text" name="aut_email" id="aut_email" value="<?= $resultats['aut_email']; ?>"/></p>

    <p><label for="aut_password">Mot de passe : </label><input type="password" name="aut_password" id="aut_pasword" value="<?= $resultats['aut_password']; ?>"/></p>

    <p><label for="aut_password2">Mot de passe : </label><input type="password" name="aut_password2" id="aut_pasword2" value="<?= $resultats['aut_password2']; ?>"/></p>

    <p><input type="submit" value="Ajouter" /></p>

</form>