<!-- Ce fichier correspond à la vue repris dans la variable $vue -->

<h1>Connexion</h1>

<form method="POST" action="login.php">

    <p><label for="aut_email">Email : </label><input type="text" name="aut_email" id="aut_email" /></p>

    <p><label for="aut_email">Mot de passe : </label><input type="password" name="aut_password" id="aut_password" /></p>

    <p><input type="submit" value="Connexion" /></p>

</form>